global.MESSAGE_TYPES = {
  AUTHENTICATION: 0,
  REGISTER_USER: 1,
  LOGIN_USER: 2,
  GET_MESSAGES: 3,
  SEND_MESSAGE: 4,
  RECEIVE_MESSAGE: 5,
  OFFER_JOB: 6,
  GET_MATCHES: 7,
  ACCEPT_MATCH: 8,
  REJECT_MATCH: 9
};

global.USER_TYPES = {
  EMPLOYEE: 0,
  RECRUITER: 1
};

global.secretJWT = 'jkhgjkg345kuihfdf,nmn354435kjwmsdfsd';
